onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top_controller/Clk
add wave -noupdate /top_controller/as_nReset
add wave -noupdate /top_controller/as_Address
add wave -noupdate /top_controller/as_ChipSelect
add wave -noupdate /top_controller/as_Read
add wave -noupdate /top_controller/as_Write
add wave -noupdate /top_controller/as_ReadData
add wave -noupdate /top_controller/as_WriteData
add wave -noupdate /top_controller/am_address
add wave -noupdate /top_controller/am_byteEenable
add wave -noupdate /top_controller/am_read
add wave -noupdate /top_controller/am_readData
add wave -noupdate /top_controller/am_write
add wave -noupdate /top_controller/am_writeData
add wave -noupdate /top_controller/am_waitrequest
add wave -noupdate /top_controller/am_ReadDataValid
add wave -noupdate /top_controller/am_BurstCount
add wave -noupdate /top_controller/DCX
add wave -noupdate /top_controller/WRX
add wave -noupdate /top_controller/CSX
add wave -noupdate /top_controller/LCD_ON
add wave -noupdate /top_controller/RESX
add wave -noupdate /top_controller/DATA_CMD_out
add wave -noupdate /top_controller/RDX
add wave -noupdate /top_controller/data_sig
add wave -noupdate /top_controller/rdreq_sig
add wave -noupdate /top_controller/sclr_sig
add wave -noupdate /top_controller/wrreq_sig
add wave -noupdate /top_controller/almost_empty_sig
add wave -noupdate /top_controller/almost_full_sig
add wave -noupdate /top_controller/empty_sig
add wave -noupdate /top_controller/full_sig
add wave -noupdate /top_controller/q_sig
add wave -noupdate /top_controller/usedw_sig
add wave -noupdate /top_controller/DCXi_sig
add wave -noupdate /top_controller/DATA_CMD_sig
add wave -noupdate /top_controller/START_sig
add wave -noupdate /top_controller/STOP_sig
add wave -noupdate /top_controller/as_write_sig
add wave -noupdate /top_controller/fifo_inst/clock
add wave -noupdate /top_controller/fifo_inst/data
add wave -noupdate /top_controller/fifo_inst/rdreq
add wave -noupdate /top_controller/fifo_inst/sclr
add wave -noupdate /top_controller/fifo_inst/wrreq
add wave -noupdate /top_controller/fifo_inst/almost_empty
add wave -noupdate /top_controller/fifo_inst/almost_full
add wave -noupdate /top_controller/fifo_inst/empty
add wave -noupdate /top_controller/fifo_inst/full
add wave -noupdate /top_controller/fifo_inst/q
add wave -noupdate /top_controller/fifo_inst/usedw
add wave -noupdate /top_controller/fifo_inst/sub_wire0
add wave -noupdate /top_controller/fifo_inst/sub_wire1
add wave -noupdate /top_controller/fifo_inst/sub_wire2
add wave -noupdate /top_controller/fifo_inst/sub_wire3
add wave -noupdate /top_controller/fifo_inst/sub_wire4
add wave -noupdate /top_controller/fifo_inst/sub_wire5
add wave -noupdate /top_controller/fifo_inst/scfifo_component/data
add wave -noupdate /top_controller/fifo_inst/scfifo_component/clock
add wave -noupdate /top_controller/fifo_inst/scfifo_component/wrreq
add wave -noupdate /top_controller/fifo_inst/scfifo_component/rdreq
add wave -noupdate /top_controller/fifo_inst/scfifo_component/aclr
add wave -noupdate /top_controller/fifo_inst/scfifo_component/sclr
add wave -noupdate /top_controller/fifo_inst/scfifo_component/q
add wave -noupdate /top_controller/fifo_inst/scfifo_component/eccstatus
add wave -noupdate /top_controller/fifo_inst/scfifo_component/usedw
add wave -noupdate /top_controller/fifo_inst/scfifo_component/full
add wave -noupdate /top_controller/fifo_inst/scfifo_component/empty
add wave -noupdate /top_controller/fifo_inst/scfifo_component/almost_full
add wave -noupdate /top_controller/fifo_inst/scfifo_component/almost_empty
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_count_id
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_read_id
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_full_flag
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_empty_flag
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_almost_full_flag
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_almost_empty_flag
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_set_q_to_x
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_set_q_to_x_by_empty
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_tmp_q
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_eccstatus
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_write_id
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_write_latency1
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_write_latency2
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_write_latency3
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_wrt_count
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_empty_latency1
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_empty_latency2
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_data_ready
add wave -noupdate /top_controller/fifo_inst/scfifo_component/i_data_shown
add wave -noupdate /top_controller/MasterSlaveInterface/Clk
add wave -noupdate /top_controller/MasterSlaveInterface/as_nReset
add wave -noupdate /top_controller/MasterSlaveInterface/as_Address
add wave -noupdate /top_controller/MasterSlaveInterface/as_ChipSelect
add wave -noupdate /top_controller/MasterSlaveInterface/as_Read
add wave -noupdate /top_controller/MasterSlaveInterface/as_Write
add wave -noupdate /top_controller/MasterSlaveInterface/as_ReadData
add wave -noupdate /top_controller/MasterSlaveInterface/as_WriteData
add wave -noupdate /top_controller/MasterSlaveInterface/am_address
add wave -noupdate /top_controller/MasterSlaveInterface/am_byteEenable
add wave -noupdate /top_controller/MasterSlaveInterface/am_read
add wave -noupdate /top_controller/MasterSlaveInterface/am_readData
add wave -noupdate /top_controller/MasterSlaveInterface/am_waitrequest
add wave -noupdate /top_controller/MasterSlaveInterface/am_ReadDataValid
add wave -noupdate /top_controller/MasterSlaveInterface/am_BurstCount
add wave -noupdate /top_controller/MasterSlaveInterface/f_almost_full
add wave -noupdate /top_controller/MasterSlaveInterface/wrreq
add wave -noupdate /top_controller/MasterSlaveInterface/f_empty
add wave -noupdate /top_controller/MasterSlaveInterface/f_data
add wave -noupdate /top_controller/MasterSlaveInterface/f_usedw
add wave -noupdate /top_controller/MasterSlaveInterface/DCXi_out
add wave -noupdate /top_controller/MasterSlaveInterface/DATA_CMD_out
add wave -noupdate /top_controller/MasterSlaveInterface/START_out
add wave -noupdate /top_controller/MasterSlaveInterface/STOP_out
add wave -noupdate /top_controller/MasterSlaveInterface/as_write_out
add wave -noupdate /top_controller/MasterSlaveInterface/StartAddress
add wave -noupdate /top_controller/MasterSlaveInterface/PictureLength
add wave -noupdate /top_controller/MasterSlaveInterface/StartAddress_modified
add wave -noupdate /top_controller/MasterSlaveInterface/PictureLength_modified
add wave -noupdate /top_controller/MasterSlaveInterface/asserted
add wave -noupdate /top_controller/MasterSlaveInterface/DATA_CMD
add wave -noupdate /top_controller/MasterSlaveInterface/START
add wave -noupdate /top_controller/MasterSlaveInterface/STOP
add wave -noupdate /top_controller/MasterSlaveInterface/DCXi
add wave -noupdate /top_controller/MasterSlaveInterface/State
add wave -noupdate /top_controller/MasterSlaveInterface/NextState
add wave -noupdate /top_controller/MasterSlaveInterface/burstMode
add wave -noupdate /top_controller/MasterSlaveInterface/burst_cycles_left
add wave -noupdate /top_controller/MasterSlaveInterface/burstIntermediate
add wave -noupdate /top_controller/MasterSlaveInterface/as_ReadData_t
add wave -noupdate /top_controller/LCD_Control/Clk
add wave -noupdate /top_controller/LCD_Control/as_nReset
add wave -noupdate /top_controller/LCD_Control/rdreq
add wave -noupdate /top_controller/LCD_Control/sclr
add wave -noupdate /top_controller/LCD_Control/almost_empty
add wave -noupdate /top_controller/LCD_Control/almost_full
add wave -noupdate /top_controller/LCD_Control/empty
add wave -noupdate /top_controller/LCD_Control/full
add wave -noupdate /top_controller/LCD_Control/q
add wave -noupdate -format Analog-Step -height 74 -max 16.0 /top_controller/LCD_Control/usedw
add wave -noupdate /top_controller/LCD_Control/DCXi_in
add wave -noupdate /top_controller/LCD_Control/DATA_CMD_in
add wave -noupdate /top_controller/LCD_Control/START_in
add wave -noupdate /top_controller/LCD_Control/STOP_in
add wave -noupdate /top_controller/LCD_Control/as_write_in
add wave -noupdate /top_controller/LCD_Control/DCX
add wave -noupdate /top_controller/LCD_Control/WRX
add wave -noupdate /top_controller/LCD_Control/CSX
add wave -noupdate /top_controller/LCD_Control/LCD_ON
add wave -noupdate /top_controller/LCD_Control/RESX
add wave -noupdate /top_controller/LCD_Control/RDX
add wave -noupdate /top_controller/LCD_Control/DATA_CMD_out
add wave -noupdate /top_controller/LCD_Control/DATA_CMD_register
add wave -noupdate /top_controller/LCD_Control/State2
add wave -noupdate /top_controller/LCD_Control/NextState2
add wave -noupdate /top_controller/LCD_Control/CSX_reg
add wave -noupdate /top_controller/LCD_Control/DCX_reg
add wave -noupdate /top_controller/LCD_Control/WRX_reg
add wave -noupdate /top_controller/LCD_Control/finished
add wave -noupdate /top_controller/LCD_Control/State3
add wave -noupdate /top_controller/LCD_Control/NextState3
add wave -noupdate /top_controller/LCD_Control/start_transfer_of_pixel
add wave -noupdate /top_controller/LCD_Control/sel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {17416 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 185
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 1
configure wave -timelineunits ms
update
WaveRestoreZoom {12692 ps} {27127 ps}
